# Generated by Django 4.1 on 2022-09-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='image',
        ),
    ]
